spring:
  datasource:
    url: jdbc:h2:file:./salary
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  error:
    include-message: always

app:
  seed:
    enabled: false
